### ISSUE TITLE
Optional File Creation

### ISSUE THREAD

**Issue by rawkode** [tmrts/boilr#10]
It would be good if we could specify that a file is only created when an assertion is true, rather than every file inside of `template` being created

**Comment by tmrts** [comment]
I'm thinking we might put the file contents inside an if conditional and skip the file if it's empty.

I'm also up for other suggestions, any ideas?

**Comment by rawkode** [comment]
@tmrts I had the same thought, skip empty files, when I was thinking about it :+1:

**Comment by tmrts** [comment]
Another option would be to use the file names like so: `{{if BlacklistEnabled}}blacklist.txt{{end}}` (This is the complete name of the file)

**Comment by rawkode** [comment]
I guess file names with spaces and special characters aren't as fussy as they used to be, thanks to fancy zsh plugins, and the like; I'd still tend to avoid them when possible though.

Not sure if this would be over-complicating, but it could become part of the schema:

```
{
    "application_builder": [ "docker-compose", "vagrant" ],
    "files": {
        "application_builder[docker-compose]": [
            "docker-compose.yml",
            "opt/bin/entrypoint.sh"
        ]
    }
}
```

**Comment by tmrts** [comment]
Boilr now cleans a file if after the execution of a template, the contents consist of only whitespace characters.

Cheers :smile:
