### ISSUE TITLE
Add log levels

### ISSUE THREAD

**Issue by tmrts** [tmrts/boilr#12]
Implement logging levels for pkg `tlog`

See https://github.com/tmrts/boilr/blob/master/pkg/util/tlog/log.go#L32

**Comment by tmrts** [comment]
@rawkode: this is a low hanging fruit to learn about the boilr, I hope you enjoy it!

I'll keep filing more

**Comment by rawkode** [comment]
Thanks @tmrts 👍 

Going to check this out today :)

**Comment by rawkode** [comment]
Hi @tmrts,

```
    "github.com/tmrts/boilr/pkg/boilr"
    "github.com/tmrts/boilr/pkg/util/tlog"
    "github.com/tmrts/boilr/pkg/util/validate"
```

These imports scattered around the project mean that my local changes are neglected for the remotes. Am I doing something daft?

**Comment by tmrts** [comment]
Hi @rawkode,

If I understood your problem correctly, you are developing on `github.com/rawkode/boilr/...`,
but changes you've made are not used, since imports still use `github.com/tmrts/boilr/...`.

You can get around this by doing the following:

``` bash
go get github.com/tmrts/boilr OR git clone https://github.com/tmrts/boilr
cd $BOILR_REPO # Wherever
git remote add fork https://github.com/rawkode/boilr
```

And you can push your changes by using `git push fork <branch-id>`.

Let me know if it solves your problem

**Comment by rawkode** [comment]
I started on this and it would seem there is an error with cobra (https://github.com/spf13/cobra/issues/245) that stops flags on the root command being passed on to sub-commands.

You can see my initial code: https://github.com/tmrts/boilr/compare/master...rawkode:feature/enable-log-levels?expand=1

Any thoughts on how I should proceed?

**Comment by tmrts** [comment]
That is an annoying bug, but it's not a deal-breaker, because without log levels debug statements will be printed by default and with log levels implemented they will be ignored (unless turned on manually), so I can accept the PR
