### ISSUE TITLE
Check for updated template during "template use" and prompt for option

### ISSUE THREAD

**Issue by rawkode** [tmrts/boilr#14]
It would be cool if boilr prompted/informed people that the template they're using has been updated and if they wish to update it.

**Comment by tmrts** [comment]
After integrating version control #11 to boilr, I'm thinking of using the command `boilr template update` for updating templates.

Not sure about regularly making requests though, since it'll be slow

**Comment by rawkode** [comment]
With the recent release of `0.3.0` and the switch to `src-d/go.git`, is this something I can work on? :smile:

**Comment by tmrts** [comment]
@rawkode absolutely :smile: 

Now that we are using git for plumbing, a lot of possibilities has opened up (changelog via git log, storing metadata in .git, git hooks/subtrees etc.)

Also see #39
