### ISSUE TITLE
Allow hyphen and underscore in template-tags

### ISSUE THREAD

**Issue by ax-nathan** [tmrts/boilr#17]
It would be nice to use `-` and `_` in template tags. Is there a reason why not to do this?

**Comment by ax-nathan** [comment]
Happy to do a quick PR, if you're OK with it...

**Comment by tmrts** [comment]
Nathan thanks for trying out boilr.

I don't have a problem with hypens or underscores in the template tags, thank you for bringing it up.
The change can be made by modifying the validation pattern for the related commands like `template save`, `template use`, etc. (see https://github.com/tmrts/boilr/blob/master/pkg/cmd/save.go#L24).

Feel free to do it if you can, if not I'll implement it when I get a chance

**Comment by rawkode** [comment]
Hi @ax-nathan - if you don't have the time to work on this, just let me know and I'll pick it up. Nice idea though 👍

**Comment by rawkode** [comment]
As there's been no reply on this for over a month, I'll pick this up this afternoon
