### ISSUE TITLE
Install script broken link in Installation wiki doc

### ISSUE THREAD

**Issue by sgoings** [tmrts/boilr#2]
The [Install Script](https://github.com/tmrts/boilr/wiki/Installation#install-script) section of the Installation doc in the wiki points to a script with URL: https://github.com/tmrts/boilr/install but needs to point to:
- https://raw.githubusercontent.com/tmrts/boilr/master/install or
- https://raw.githubusercontent.com/tmrts/boilr/0.1.0/install or
- https://github.com/tmrts/boilr/releases/download/0.1.0/install

Boilr looks really neat!

**Comment by tmrts** [comment]
Thanks a lot! Just fixed the wiki link to point to the install script included in the `v0.1.0` release

**Comment by tmrts** [comment]
Also enabled public access to wiki so that people can add their own improvements.
