### ISSUE TITLE
Make directory creation permissions a more lax 755

### ISSUE THREAD

**Issue by andrewhowdencom** [tmrts/boilr#21]
Hi, 

In Linux, users that are not in the same group as the user that is not the owner of the file require the execute permission on folders to traverse that folder. 

At the minute, you're specifying 744 on created folders, which means (if I understand correctly -- a stretch) that the user not in the original group can read the folder, but not traverse it. 

Ideally, you could pick up the permissions from the machine umask, or whatever else mkdir is using to generate the inital set of permissions. 

Ref: https://github.com/tmrts/boilr/blob/04e56be23b25fd3c54e52c67d399a791daaa4bd9/pkg/util/osutil/fs.go#L49

Cheers!

**Comment by tmrts** [comment]
I agree about allowing traversal, but `umask` is already used, so that shouldn't be a problem 👍

**Comment by tmrts** [comment]
4bf5327c implements this
