### ISSUE TITLE
Cut a release. 

### ISSUE THREAD

**Issue by andrewhowdencom** [tmrts/boilr#24]
It'd be nice to get the folder changes in a distributed package. It affects us, as we create a template for PHP software called "Magento", which heavily relies on folders.

If i can help in any way, please let me know!

**Comment by tmrts** [comment]
I didn't have a chance to work on `boilr` due to me relocating. I'm planning to implement `0.3` features this weekend and cut a release 👍

**Comment by andrewhowdencom** [comment]
<3 Thanks!

**Comment by schmunk42** [comment]
ping :)

**Comment by tmrts** [comment]
@rawkode @andrewhowdencom @schmunk42 I didn't have time to work boilr for a while, but I'm resuming the work, sorry for the pause in development :frowning_face:

**Comment by schmunk42** [comment]
No need to apologize!

**Comment by andrewhowdencom** [comment]
Man, I use this tool almost daily. Super grateful for it!

**Comment by tmrts** [comment]
https://github.com/tmrts/boilr/releases/tag/0.3.0 :tada:

**Comment by andrewhowdencom** [comment]
YAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAY.

**Comment by rawkode** [comment]
Stoked :+1:

**Comment by tmrts** [comment]
@rawkode @andrewhowdencom the long wait is over :smile:
