### ISSUE TITLE
Clarify instructions for compiling from source.

### ISSUE THREAD

**Issue by ghost** [tmrts/boilr#26]
For some environments (eg fresh install of Go on Gentoo/RPi) the listed `go install` instruction will throw messages about missing packages. Instead, setting `GOPATH` and using `go get github.com/tmrts/boilr` will fetch and build the dependencies and result in the `boilr` binary in `GOPATH/bin/`.

**Comment by tmrts** [comment]
@oneirosFade thanks for the information! I updated the wiki, please take a look at  [Installation](https://github.com/tmrts/boilr/wiki/Installation) and let me know if I've missed anything

**Comment by tmrts** [comment]
Docs should be clear enough on how to compile from source, feel free to reopen if it isn't
