### ISSUE TITLE
Support spaces control in templates.

### ISSUE THREAD

**Issue by marcinpraczko** [tmrts/boilr#31]
According to this page: https://golang.org/pkg/text/template/ - section 'text and spaces' GO templating allows control spaces:

```
{{- and -}}
```

For all my test boilr is crashing when one of his syntax is used.

**Comment by tmrts** [comment]
@marcinpraczko I couldn't reproduce your error, `{{-` or `-}}` works as intended for me. 

Can you give me the error and/or the template you've used?

**Comment by tmrts** [comment]
Feel free to reopen if you can reproduce it
