### ISSUE TITLE
"[✘] environment variable ${HOME} should be set" error on Windows

### ISSUE THREAD

**Issue by flawiddsouza** [tmrts/boilr#35]
The title basically describes the error. I've created a environment variable `HOME` to my user directory but it's not getting recognized. I'm assuming Windows isn't supported, but is there a solution to this?

I built from source by running `go get github.com/tmrts/boilr`.

**Comment by flawiddsouza** [comment]
Update: Looks like it needs admin access to be run. Don't know why. Does it need that on linux or macOS? I was able to run it properly only after opening cmd as administrator.

**Comment by mattiamarchesini** [comment]
I don't know why running as administrator solved the problem for you.

What I did is adding a variable called HOME in the Environment Variables and it started working.
