### ISSUE TITLE
Malformed zipURL on Windows

### ISSUE THREAD

**Issue by flawiddsouza** [tmrts/boilr#36]
templateURL == tmrts/boilr-license
zipURL == https://codeload.github.com/tmrts\boilr-license\zip\master

This leads to an error, which is:
[✘] download: zip: not a valid zip file

The culprit:
This line from boilr/pkg/host/github.go:
`return "https://codeload.github.com/" + filepath.Join(url, "/zip/"+version)`

This happens because:
"Package filepath implements utility routines for manipulating filename paths in a way compatible with the target operating system-defined file paths." As Windows file paths are backward slashed by default, this malformed zipURL is the result.

Suggested fix:
`return "https://codeload.github.com/" + url + "/zip/" + version`

**Comment by tmrts** [comment]
@flawiddsouza sorry for the late response and thanks for the report :smile: the bug is fixed now
