### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by stefanwalther** [tmrts/boilr#78]
I love this project and use it for a while ...

It seems that there are quite a few folks out there being willing to contribute (see the PRs).

@tmrts Can we make this repo open to other contributors + maintainers? It would be really great to get some traction on this repo ...

Regards
Stefan

**Comment by jackwilsdon** [comment]
Check #65 — there is a fork there which seems to have a bit more life in it.

**Comment by stefanwalther** [comment]
Thanks!!!
